# Generated by Django 5.0.6 on 2024-06-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateField(auto_created=True)),
                ('device_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('datetime_activated', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('reserve_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
