# Generated by Django 5.0.6 on 2024-06-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(default='offline', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
